Conjugate gradient
matthieumeo/pyxu pull request #15
Opened 2022-02-25 15:37 UTC by joanrue

Added the Conjugate Gradient Method iterative solver based on the Sepand's Solver.py base class.

2022-03-01 15:05 UTC, joanrue commented
My last commit should have been: 
"[solver/CG] Refactor to leverage base classes' functionalities"
"Stopping criterion is an instance of opt.stop.AbsError instead of created from scratch. Fit function is called from base class instead of defining it from scratch. Also added a broadcastable test for b and x0"

2022-03-01 15:16 UTC, SepandKashani requested changes

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/abc/solver.py
> +            super().__init__()
ok based on our discussion.

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +    * :math:`\mathcal{A}: \mathbb{R}^M\times^N` is a *symmetric* *positive definite* matrix.
*positive def* OPERATOR, not necessarily a matrix. (We only need to know how to apply the op afterall.)

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        stop_crit: pycs.StoppingCriterion = None,
If `tol` is provided in `fit()`, then you should not have `stop_crit` in the signature anymore.
It is the job of `fit()` to construct the AbsErr stop_crit and call `super().fit()` with it.

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        Parameters
Add an empty line before `Parameters`.

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +           (..., N) Starting guess(es) for the solution(s). Defaults to a zero NDArray if unspecified.
Prefer the term "initial point" to "starting guess".

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        rr = (r * r).sum(-1)[..., None]
`rr = xp.linalg.norm(r, ord=2, axis=-1, keepdims=True` should work and avoids 2 temporary arrays in the process.

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        alpha = rr / (p * ap).sum(-1)[..., None]
`rr / (p*ap).sum(axis=-1, keepdims=True)` avoids having to do the `[...,None]` indexing at the end.

2022-03-01 15:16 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        beta = (r * r).sum(-1)[..., None] / rr
Same comment as above.

2022-03-01 20:44 UTC, SepandKashani requested changes
Looking better. Still some things to tackle.

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +    * :math:`\mathcal{A}: \mathbb{R}^M\times^N` is a *symmetric* *positive definite* operator.
You use both M and N as indices here, but A must be square.
Double-check the whole docstring and standardize on one letter only.

Also, rewrite this as `\mathcal{A}: \mathbb{R}^{N} \to \mathbb{R}^{N}`

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        log_var: pyct.VarName = ("x",),
I missed this last time: why are `folder`, `exist_ok`, `writeback_rate`, `verbosity` missing here?

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +    * :math:`\mathcal{A}: \mathbb{R}^M\times^N` is a *symmetric* *positive definite* operator.
In `CG.fit()`, the docstring says "the minimization problem defined in :py:meth:`CG.__init__`", but Ax=b is not a minimization problem.
You should instead write \argmin_{x\in\bR^{N}} ||Ax - b||_{2}^{2}, where A is ...

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        self._mstate["r"] = r = self._b - self._a.apply(x0)
`= r =` is useless.

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +    @pycrt.enforce_precision(o=True)
No decorator should be used here. If your `m_init` and `m_step` are correct, the output dtype should match `b` and `x0`s dtype.

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        try:
`AbsError` will check `tol > 0`: don't need to test again here.

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +            x0 = xp.zeros((1, self._b.shape[-1]), dtype=pycrt.getPrecision().value)
`dtype = self._b.dtype`.

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +def is_broadcastable(arr1, arr2):
Use `numpy.broadcast_shapes()` instead of rolling out your own function.

2022-03-01 20:44 UTC, SepandKashani commented on src/pycsou/opt/solver/cg.py
> +        return super().fit(x0, mode=mode, stop_crit=stop_crit)
I now have a doubt on this. Leave as-is and see if it runs.

2022-03-02 09:08 UTC, SepandKashani approved these changes

2022-03-02 09:08 UTC, merged