Coerce mod agnostic
matthieumeo/pyxu pull request #16
Opened 2022-03-01 10:09 UTC by joanrue

Coerce() function can now handle cupy and dask arrays.

2022-03-01 10:52 UTC, SepandKashani reviewed
Have yet to look at `cg.py`.

2022-03-01 10:52 UTC, SepandKashani commented on src/pycsou/abc/solver.py
> +            super().__init__()
Not really needed, but ok.

2022-03-01 10:52 UTC, SepandKashani commented on src/pycsou/runtime/__init__.py
> +    try:
I don't quite agree with all the steps here. Let's talk about this in the afternoon.

2022-03-01 15:05 UTC, SepandKashani requested changes
Some minor things to fix. (See comments.)
For `cg.py`, I suggest removing it entirely from this pull request and adding it only to #15

2022-03-01 15:05 UTC, SepandKashani commented on src/pycsou/runtime/__init__.py
> +import pycsou.util as pycu
Not required anymore.

2022-03-01 15:05 UTC, SepandKashani commented on src/pycsou/abc/solver.py
> +            super().__init__()
ok, based on our discussion.

2022-03-03 07:48 UTC, SepandKashani commented
@joanrue Are you currently working on this?
Only `runtime/__init__.py` should be modified in this pull request. (No `xp` inference needed, just drop the `casting=` parameter and it should be good to go.

2022-03-03 12:39 UTC, joanrue commented
@SepandKashani Sorry made a mistake before you explained me the stash (This should not happen again). I fixed the conflict and I think this branch is ready to be merged.

2022-03-03 12:44 UTC, SepandKashani approved these changes
Looks good.

2022-03-03 13:56 UTC, merged